### PR TITLE
joyent/node-docker-registry-client#23 Namespace validation too strict

### PR DESCRIPTION
**Pull request by jzaefferer**
Allow dot in namespace, to accommodate GitLab repos

Patch for #23. The new tests pass.

### CODE REVIEW

**Comment by jzaefferer** [comment]
@trentm @twhiteman any feedback on this? I'm hoping to get this merged and published, to avoid another temporary fork. Let me know if I can help in any way to move things forward.

**Comment by trentm** [comment]
@jzaefferer Thanks. Can you also update the error message lower down:

```
        if (! VALID_NS.test(ns)) {
            throw new Error('invalid repository namespace, may only contain ' +
                '[a-z0-9_-] characters: ' + ns);
        }
```

The relevant Docker distribution comparison parsing is: https://github.com/docker/distribution/blob/5db89f0ca68677abc5eefce8f2a0a772c98ba52d/reference/regexp.go#L6-L20
which includes some complexity to avoid things like consecutive periods, dashes, etc. as shown by these tests: https://github.com/docker/distribution/blob/5db89f0ca68677abc5eefce8f2a0a772c98ba52d/reference/normalize_test.go#L90-L119
It would be nice eventually to update this modules parsing to comply with that, but that definitely could be in a separate change.

**Comment by jzaefferer** [comment]
> Can you also update the error message lower down:

Done!

> It would be nice eventually to update this modules parsing to comply with that, but that definitely could be in a separate change.

Yeah, that's quite a big task compared to accepting one extra dot character.

**Comment by trentm** [comment]
CR: https://cr.joyent.us/#/c/2662/

@jzaefferer  Thanks! I'll have this in shortly.

This repo (and most of the repos associated with Triton) don't use GitHub PRs, but instead we use a Gerrit installation at https://cr.joyent.us. There is a note (that is easy to miss) at the top of the README.md, and GH doesn't support turning off PRs for a given repo. Getting used to using Gerrit for the first time can be quite a hurdle, so I've imported your patch there (at the CR link at the top of this comment). If you are able, please use cr.joyent.us for future patches. Thanks.

**Comment by trentm** [comment]
Merged, and docker-registry-client@3.2.12. Thanks!

**Comment by jzaefferer** [comment]
> There is a note (that is easy to miss) at the top of the README.md

Yeah, really easy to miss. It might help to make a copy of the contributing.md file and add it to the repo. At least then anyone opening an issue or PR gets a notice to look at that first.

Anyway, thanks for merging and publishing. Cheers!

**Pull request closed without merging**
